apiVersion: v1
kind: Namespace
metadata:
  name: my-react-app
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-react-app
  namespace: my-react-app
  labels:
    app: my-react-app
spec:
  selector:
    matchLabels:
      app: my-react-app
  replicas: 2
  template:
    metadata:
      labels:
        app: my-react-app
    spec:
      containers:
        - name: my-react-app
          image: ghcr.io/spotify-portal-public-demo/my-react-app:latest # {"$imagepolicy": "flux-system:my-react-app"}
          imagePullPolicy: Always
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "256Mi"
              cpu: "200m"
---
apiVersion: v1
kind: Service
metadata:
  name: my-react-app
  namespace: my-react-app
  labels:
    app: my-react-app
spec:
  clusterIP: None
  selector:
    app: my-react-app
  ports:
    - name: http
      port: 3000
